name: Publish Schemas

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build-documentation:
    runs-on: ubuntu-24.04
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v6
      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v6
      - name: Build Static Page
        run: |
          poetry run python -m exasol.schemas --schemas schemas --examples examples --destination gh-pages
      - name: Verify Generated Index
        run: test -f gh-pages/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: gh-pages

  deploy-documentation:
    if: ${{ github.event_name == 'push' }}
    needs: [ build-documentation ]
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
